import type { Candidate } from "@/types/candidate";

export const MOCK_CANDIDATES: Candidate[] = [
  {
    id: "1",
    name: "Arjun Mehta",
    score: 92,
    strengths: [
      "Distributed Systems",
      "Microservices Architecture", 
      "Cross-functional Leadership",
      "AWS & GCP Expertise",
    ],
    gaps: [
      "GraphQL Federation",
      "Multi-region Deployment",
    ],
    recommended_role: "Principal Backend Engineer",
    experience_years: 8,
    current_company: "Oracle",
    location: "Bangalore, India",
  },
  {
    id: "2",
    name: "Priya Sharma",
    score: 87,
    strengths: [
      "Kubernetes & Docker",
      "CI/CD Pipeline Design",
      "Infrastructure as Code",
      "SRE Best Practices",
    ],
    gaps: [
      "Service Mesh (Istio)",
      "FinOps & Cost Optimization",
    ],
    recommended_role: "Senior DevOps Engineer",
    experience_years: 6,
    current_company: "Flipkart",
    location: "Hyderabad, India",
  },
  {
    id: "3",
    name: "Rahul Krishnan",
    score: 78,
    strengths: [
      "Python & Spark",
      "ML Model Deployment",
      "Data Pipeline Engineering",
    ],
    gaps: [
      "Real-time Stream Processing",
      "MLOps Maturity",
      "Cross-team Documentation",
    ],
    recommended_role: "Data Engineer",
    experience_years: 4,
    current_company: "Swiggy",
    location: "Chennai, India",
  },
  {
    id: "4",
    name: "Kavitha Reddy",
    score: 95,
    strengths: [
      "System Design Expert",
      "Global Team Collaboration",
      "API Platform Architecture",
      "Technical Mentorship",
      "Event-Driven Systems",
    ],
    gaps: [
      "Rust/WebAssembly",
    ],
    recommended_role: "Staff Engineer - Platform",
    experience_years: 10,
    current_company: "Google",
    location: "Bangalore, India",
  },
  {
    id: "5",
    name: "Aditya Nair",
    score: 71,
    strengths: [
      "React & Next.js",
      "TypeScript",
      "Design Systems",
    ],
    gaps: [
      "Backend Integration",
      "Performance Optimization",
      "Accessibility Standards",
      "Scalability Patterns",
    ],
    recommended_role: "Frontend Engineer",
    experience_years: 3,
    current_company: "Razorpay",
    location: "Pune, India",
  },
];

// Additional mock candidates for the heatmap visualization
export const EXTENDED_MOCK_CANDIDATES: Candidate[] = [
  ...MOCK_CANDIDATES,
  {
    id: "6",
    name: "Sneha Gupta",
    score: 83,
    strengths: ["Java", "Spring Boot", "Microservices", "Kafka"],
    gaps: ["Cloud Native Patterns", "Observability"],
    recommended_role: "Backend Engineer",
    experience_years: 5,
    current_company: "Infosys",
    location: "Mumbai, India",
  },
  {
    id: "7",
    name: "Vikram Singh",
    score: 89,
    strengths: ["Go", "gRPC", "Kubernetes", "Terraform"],
    gaps: ["Frontend Basics"],
    recommended_role: "Platform Engineer",
    experience_years: 7,
    current_company: "Uber",
    location: "Delhi, India",
  },
  {
    id: "8",
    name: "Ananya Iyer",
    score: 65,
    strengths: ["Node.js", "MongoDB", "Express"],
    gaps: ["System Design", "Scalability", "Testing Practices"],
    recommended_role: "Junior Backend Engineer",
    experience_years: 2,
    current_company: "TCS",
    location: "Kochi, India",
  },
  {
    id: "9",
    name: "Rohit Verma",
    score: 91,
    strengths: ["ML Engineering", "PyTorch", "MLOps", "Data Pipelines"],
    gaps: ["Real-time Inference"],
    recommended_role: "ML Engineer",
    experience_years: 6,
    current_company: "Amazon",
    location: "Bangalore, India",
  },
  {
    id: "10",
    name: "Meera Patel",
    score: 74,
    strengths: ["PostgreSQL", "Redis", "Data Modeling"],
    gaps: ["Distributed Databases", "Sharding Strategies"],
    recommended_role: "Database Engineer",
    experience_years: 4,
    current_company: "Zoho",
    location: "Chennai, India",
  },
];
