export const MOCK_CANDIDATES = [
    {
        id: '1',
        full_name: 'Aarav Patel',
        technical_dna: { core: ['React', 'Next.js', 'TypeScript'], adjacent: ['Node.js', 'PostgreSQL'] },
        readiness_score: 88,
        upskilling_path: ['Advanced System Design', 'Kubernetes Basics'],
    },
    {
        id: '2',
        full_name: 'Sneha Gupta',
        technical_dna: { core: ['Java', 'Spring Boot', 'Microservices'], adjacent: ['AWS', 'Kafka'] },
        readiness_score: 92,
        upskilling_path: ['GraphQL Federation', 'Service Mesh'],
    },
    {
        id: '3',
        full_name: 'Rohan Sharma',
        technical_dna: { core: ['Python', 'Django', 'FastAPI'], adjacent: ['Docker', 'Redis'] },
        readiness_score: 75,
        upskilling_path: ['Cloud Native Patterns', 'CI/CD Pipelines'],
    },
    {
        id: '4',
        full_name: 'Priya Singh',
        technical_dna: { core: ['Angular', 'RxJS', '.NET Core'], adjacent: ['Azure', 'SQL Server'] },
        readiness_score: 81,
        upskilling_path: ['Modern React Hooks', 'Tailwind CSS'],
    },
    {
        id: '5',
        full_name: 'Vikram Malhotra',
        technical_dna: { core: ['Go', 'gRPC', 'Kubernetes'], adjacent: ['Terraform', 'Prometheus'] },
        readiness_score: 95,
        upskilling_path: ['Advanced Security', 'Multi-Region Architecture'],
    },
    {
        id: '6',
        full_name: 'Ananya Das',
        technical_dna: { core: ['Vue.js', 'Nuxt', 'Firebase'], adjacent: ['GCP', 'Node.js'] },
        readiness_score: 78,
        upskilling_path: ['React Patterns', 'State Management (Redux/Zustand)'],
    },
    {
        id: '7',
        full_name: 'Rahul Verma',
        technical_dna: { core: ['Ruby on Rails', 'PostgreSQL', 'Redis'], adjacent: ['Heroku', 'Sidekiq'] },
        readiness_score: 85,
        upskilling_path: ['Containerization (Docker)', 'Serverless Functions'],
    },
    {
        id: '8',
        full_name: 'Meera Iyer',
        technical_dna: { core: ['Swift', 'iOS', 'Combine'], adjacent: ['Objective-C', 'Fastlane'] },
        readiness_score: 70,
        upskilling_path: ['Backend Basics', 'API Design'],
    },
    {
        id: '9',
        full_name: 'Arjun Nair',
        technical_dna: { core: ['Kotlin', 'Android', 'Jetpack Compose'], adjacent: ['Java', 'Gradle'] },
        readiness_score: 72,
        upskilling_path: ['System Design for Mobile', 'GraphQL'],
    },
    {
        id: '10',
        full_name: 'Kavita Reddy',
        technical_dna: { core: ['Rust', 'WebAssembly', 'Tokio'], adjacent: ['C++', 'Linux'] },
        readiness_score: 90,
        upskilling_path: ['Distributed Tracing', 'Cloud Scaling'],
    },
    {
        id: '11',
        full_name: 'Sanjay Kumar',
        technical_dna: { core: ['PHP', 'Laravel', 'MySQL'], adjacent: ['Vue.js', 'Apache'] },
        readiness_score: 65,
        upskilling_path: ['Modern Node.js', 'NoSQL Databases'],
    },
    {
        id: '12',
        full_name: 'Neha Kapoor',
        technical_dna: { core: ['Data Science', 'Python', 'Pandas'], adjacent: ['Scikit-learn', 'SQL'] },
        readiness_score: 80,
        upskilling_path: ['MLOps (MLflow)', 'API Deployment'],
    },
    {
        id: '13',
        full_name: 'Amit Joshi',
        technical_dna: { core: ['C#', '.NET', 'Blazor'], adjacent: ['Azure DevOps', 'PowerShell'] },
        readiness_score: 83,
        upskilling_path: ['Micro-frontends', 'React Integration'],
    },
    {
        id: '14',
        full_name: 'Divya Rao',
        technical_dna: { core: ['Elixir', 'Phoenix', 'LiveView'], adjacent: ['Erlang', 'PostgreSQL'] },
        readiness_score: 89,
        upskilling_path: ['Kubernetes Operations', 'Advanced Monitoring'],
    },
    {
        id: '15',
        full_name: 'Aditya Mishra',
        technical_dna: { core: ['Scala', 'Akka', 'Spark'], adjacent: ['Hadoop', 'Kafka'] },
        readiness_score: 91,
        upskilling_path: ['Cloud Native Data', 'Streaming Architecture'],
    },
    {
        id: '16',
        full_name: 'Pooja Choudhary',
        technical_dna: { core: ['Flutter', 'Dart', 'Firebase'], adjacent: ['Android', 'iOS'] },
        readiness_score: 76,
        upskilling_path: ['State Management Patterns', 'Native Modules'],
    },
    {
        id: '17',
        full_name: 'Rajesh Khanna',
        technical_dna: { core: ['Perl', 'Bash', 'Linux Admin'], adjacent: ['AWS', 'Nagios'] },
        readiness_score: 60,
        upskilling_path: ['Modern DevOps (Terraform)', 'Python/Go'],
    },
    {
        id: '18',
        full_name: 'Simran Kaur',
        technical_dna: { core: ['QA Automation', 'Selenium', 'Java'], adjacent: ['Jenkins', 'TestNG'] },
        readiness_score: 79,
        upskilling_path: ['Cypress/Playwright', 'CI/CD Integration'],
    },
    {
        id: '19',
        full_name: 'Varun Dhawan',
        technical_dna: { core: ['Salesforce', 'Apex', 'Lightning'], adjacent: ['Java', 'SQL'] },
        readiness_score: 74,
        upskilling_path: ['Integration Patterns', 'Heroku'],
    },
    {
        id: '20',
        full_name: 'Isha Maloney',
        technical_dna: { core: ['Cybersecurity', 'Python', 'Kali Linux'], adjacent: ['Network+', 'AWS Security'] },
        readiness_score: 87,
        upskilling_path: ['DevSecOps', 'Compliance Automation'],
    }
];
